version: 2
jobs:
    build:
        docker:
            - image: byuoitav/build-env:master

        working_directory: /go/src/github.com/byuoitav/raspi-deployment-microservice

        steps:
            - checkout
            - run: |
                gvt fetch -branch $CIRCLE_BRANCH github.com/byuoitav/authmiddleware
                gvt fetch -branch $CIRCLE_BRANCH github.com/byuoitav/av-api/dbo
                gvt fetch -branch $CIRCLE_BRANCH github.com/byuoitav/configuration-database-microservice/structs
                gvt fetch -branch $CIRCLE_BRANCH github.com/byuoitav/pi-designation-microservice/accessors
                gvt fetch -branch $CIRCLE_BRANCH github.com/fatih/color
            - setup_remote_docker
            - run: | 
                make docker
                ./deploy.sh $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA2 $CIRCLE_BRANCH
